[package]
name = "aurexvideo"
version = "0.2.4"
description = "AurexVideo - Automated Video Production Engine"
authors = ["Henry"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
tar = "0.4"
flate2 = "1"
zip = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
