const state = { context: {}, overview: {}, products: [], records: [], brand: "", period: "7d", status: "all", query: "" };
const elements = Object.fromEntries([
  "brandSelect", "periodSelect", "searchInput", "statusSelect", "refreshButton", "syncState", "shopeeState", "shopeeBadge", "facebookState", "facebookBadge",
  "kpiClicks", "kpiClicksDetail", "kpiOrders", "kpiOrdersDetail", "kpiGmv", "kpiGmvDetail", "kpiCommission", "kpiCommissionDetail", "recordsBody", "recordsCount", "toast",
].map((id) => [id, document.querySelector(`#${id}`)]));

function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char])); }
function showToast(message, error = false) { elements.toast.textContent = message; elements.toast.className = `toast visible${error ? " error" : ""}`; clearTimeout(showToast.timer); showToast.timer = setTimeout(() => { elements.toast.className = "toast"; }, 3400); }
function queryString(params) { const query = new URLSearchParams(Object.entries(params).filter(([, value]) => value)); return query.size ? `?${query}` : ""; }
async function request(url, options = {}) { const response = await fetch(url, { cache: "no-store", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const payload = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(payload.error || `HTTP ${response.status}`); error.status = response.status; throw error; } return payload; }
function unavailable(error) { return error?.status === 404 || error?.status === 501; }
function list(value) { return Array.isArray(value) ? value : []; }
function number(value) { const numeric = Number(value); return Number.isFinite(numeric) ? numeric : 0; }
function money(value) { return new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(number(value)); }
function count(value) { return new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 0 }).format(number(value)); }
function pick(object, keys, fallback = "") { for (const key of keys) if (object?.[key] !== undefined && object?.[key] !== null && object[key] !== "") return object[key]; return fallback; }
function metric(overview, names) { return pick(overview?.kpis || overview?.metrics || overview, names, 0); }

function readBrands(context) { return list(context.brands || context.items || context.data).map((brand) => typeof brand === "string" ? { id: brand, name: brand } : { id: pick(brand, ["id", "slug", "value", "brandId"]), name: pick(brand, ["name", "title", "label", "id", "slug"]) }).filter((brand) => brand.id); }
function renderBrands() { const brands = readBrands(state.context); const requested = state.brand || pick(state.context, ["activeBrandId", "defaultBrandId", "brandId"]); state.brand = brands.some((brand) => brand.id === requested) ? requested : (brands[0]?.id || requested || ""); elements.brandSelect.replaceChildren(); if (!brands.length) elements.brandSelect.append(new Option("Chưa có Brand", "")); else brands.forEach((brand) => elements.brandSelect.append(new Option(brand.name, brand.id, false, brand.id === state.brand))); elements.brandSelect.disabled = !brands.length; }

function platform(context, key) { const platforms = context.platforms || context.connections || context.integrations || {}; return platforms[key] || platforms[key.toLowerCase()] || context[key] || {}; }
function renderPlatform(key, label) { const item = platform(state.context, key); const configured = Boolean(pick(item, ["connected", "configured", "active", "ok"], false)); const text = pick(item, ["name", "accountName", "pageName", "shopName", "message"], configured ? `Đã kết nối ${label}` : "Chưa kết nối"); const badge = configured ? "Sẵn sàng" : "Chưa kết nối"; const stateElement = elements[`${key}State`]; const badgeElement = elements[`${key}Badge`]; stateElement.textContent = text; badgeElement.textContent = badge; badgeElement.className = `status-pill ${configured ? "ok" : "warn"}`; }
function renderConnections() { renderPlatform("shopee", "Shopee"); renderPlatform("facebook", "Facebook"); }
function renderKpis() { const values = { clicks: metric(state.overview, ["clicks", "totalClicks"]), orders: metric(state.overview, ["orders", "totalOrders"]), gmv: metric(state.overview, ["gmv", "totalGmv", "revenue"]), commission: metric(state.overview, ["commission", "totalCommission", "earnings"]) }; const details = state.overview?.changes || state.overview?.comparison || {}; elements.kpiClicks.textContent = count(values.clicks); elements.kpiOrders.textContent = count(values.orders); elements.kpiGmv.textContent = money(values.gmv); elements.kpiCommission.textContent = money(values.commission); ["Clicks", "Orders", "Gmv", "Commission"].forEach((name) => { const key = name.toLowerCase(); const change = pick(details, [key, `${key}Change`], ""); elements[`kpi${name}Detail`].textContent = change ? String(change) : "Trong khoảng đã chọn"; }); }

function normaliseRecord(item) { const type = String(pick(item, ["type", "recordType", "kind"], item.productId ? "product" : item.campaignId ? "campaign" : "link")).toLowerCase(); return { id: pick(item, ["id", "linkId", "productId", "campaignId"]), type: ["link", "product", "campaign"].includes(type) ? type : "link", name: pick(item, ["name", "title", "productName", "linkName", "campaignName"], "Chưa đặt tên"), subtitle: pick(item, ["shortUrl", "url", "sku", "code", "id"]), campaign: pick(item, ["campaign", "campaignName", "campaignTitle"], "—"), status: String(pick(item, ["status", "state"], "active")).toLowerCase(), clicks: pick(item, ["clicks", "totalClicks"], 0), orders: pick(item, ["orders", "totalOrders"], 0), gmv: pick(item, ["gmv", "totalGmv", "revenue"], 0), commission: pick(item, ["commission", "earnings", "totalCommission"], 0), raw: item }; }
function collectRecords() { const overviewRecords = list(state.overview.records || state.overview.links || state.overview.campaigns); const productRecords = list(state.products.products || state.products.items || state.products.data || state.products); const combined = [...overviewRecords, ...productRecords].map(normaliseRecord); return combined.filter((record, index, all) => record.id ? all.findIndex((entry) => entry.id === record.id) === index : true); }
function statusLabel(status) { return ({ active: "Đang chạy", paused: "Tạm dừng", ended: "Đã kết thúc", inactive: "Không hoạt động" })[status] || (status || "—"); }
function typeLabel(type) { return ({ link: "Link", product: "Sản phẩm", campaign: "Campaign" })[type] || "Link"; }
function filteredRecords() { const needle = state.query.trim().toLocaleLowerCase("vi"); return state.records.filter((record) => (state.status === "all" || record.status === state.status) && (!needle || `${record.name} ${record.subtitle} ${record.campaign}`.toLocaleLowerCase("vi").includes(needle))); }
function renderRecords() { const records = filteredRecords(); elements.recordsCount.textContent = state.records.length ? `${records.length}/${state.records.length} mục` : "Chưa có dữ liệu"; if (!records.length) { elements.recordsBody.innerHTML = `<tr><td colspan="9" class="table-empty">${state.records.length ? "Không có mục khớp bộ lọc." : "Chưa có link, sản phẩm hoặc campaign cho Brand này."}</td></tr>`; return; } elements.recordsBody.innerHTML = records.map((record) => `<tr><td><span class="type-tag ${escapeHtml(record.type)}">${escapeHtml(typeLabel(record.type))}</span></td><td><div class="record-content"><strong title="${escapeHtml(record.name)}">${escapeHtml(record.name)}</strong><small title="${escapeHtml(record.subtitle)}">${escapeHtml(record.subtitle)}</small></div></td><td>${escapeHtml(record.campaign)}</td><td><span class="record-status ${escapeHtml(record.status)}">${escapeHtml(statusLabel(record.status))}</span></td><td class="metric-cell">${count(record.clicks)}</td><td class="metric-cell">${count(record.orders)}</td><td class="metric-cell">${money(record.gmv)}</td><td class="metric-cell">${money(record.commission)}</td><td>${record.type === "product" ? `<button class="button tiny secondary" type="button" data-create-link="${escapeHtml(record.id)}">Tạo link</button>` : ""}</td></tr>`).join(""); }

async function loadContext() { try { state.context = await request("/api/affiliate/context"); renderBrands(); renderConnections(); return true; } catch (error) { state.context = {}; renderBrands(); renderConnections(); elements.syncState.textContent = unavailable(error) ? "API affiliate chưa được bật" : "Không đọc được cấu hình"; return false; } }
async function loadData() { const params = { brand: state.brand, period: state.period, status: state.status === "all" ? "" : state.status, q: state.query }; const [overviewResult, productsResult] = await Promise.allSettled([request(`/api/affiliate/overview${queryString(params)}`), request(`/api/affiliate/products${queryString(params)}`)]); const unavailableApi = [overviewResult, productsResult].some((result) => result.status === "rejected" && unavailable(result.reason)); state.overview = overviewResult.status === "fulfilled" ? overviewResult.value : {}; state.products = productsResult.status === "fulfilled" ? productsResult.value : []; state.records = collectRecords(); renderKpis(); renderRecords(); if (overviewResult.status === "rejected" && !unavailable(overviewResult.reason)) showToast(`Không tải overview: ${overviewResult.reason.message}`, true); if (productsResult.status === "rejected" && !unavailable(productsResult.reason)) showToast(`Không tải danh sách: ${productsResult.reason.message}`, true); elements.syncState.textContent = unavailableApi ? "API affiliate chưa được bật" : (pick(state.overview, ["updatedAt", "syncedAt"], "Đã đồng bộ dữ liệu")); }
async function refresh() { elements.refreshButton.disabled = true; elements.syncState.textContent = "Đang đồng bộ..."; await loadContext(); await loadData(); elements.refreshButton.disabled = false; }
async function createLink(productId) { const record = state.records.find((item) => String(item.id) === String(productId)); if (!record) return; const button = document.querySelector(`[data-create-link="${CSS.escape(String(productId))}"]`); if (button) { button.disabled = true; button.textContent = "Đang tạo..."; } try { const result = await request("/api/affiliate/link", { method: "POST", body: JSON.stringify({ brand: state.brand, productId, product: record.raw }) }); const url = pick(result, ["url", "link", "shortUrl"]); if (url) { await navigator.clipboard?.writeText(url).catch(() => {}); showToast("Đã tạo và copy link affiliate."); } else showToast(result.message || "Đã gửi yêu cầu tạo link."); await loadData(); } catch (error) { showToast(unavailable(error) ? "Tính năng tạo link sẽ sẵn sàng khi API affiliate được bật." : error.message, true); } finally { if (button?.isConnected) { button.disabled = false; button.textContent = "Tạo link"; } } }

elements.brandSelect.addEventListener("change", () => { state.brand = elements.brandSelect.value; refresh(); });
elements.periodSelect.addEventListener("change", () => { state.period = elements.periodSelect.value; loadData(); });
elements.statusSelect.addEventListener("change", () => { state.status = elements.statusSelect.value; loadData(); });
elements.searchInput.addEventListener("input", () => { state.query = elements.searchInput.value; renderRecords(); clearTimeout(state.searchTimer); state.searchTimer = setTimeout(loadData, 300); });
elements.refreshButton.addEventListener("click", refresh);
elements.recordsBody.addEventListener("click", (event) => { const button = event.target.closest("[data-create-link]"); if (button) createLink(button.dataset.createLink); });
refresh();
