const project = new URLSearchParams(location.search).get("project");
const $ = (selector) => document.querySelector(selector);
const state = { topic: null, timer: 0, saving: false, selected: "" };
const api = async (url, options = {}) => { const response = await fetch(url, { cache: "no-store", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `HTTP ${response.status}`); return body; };
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
const token = (prefix) => `${prefix}-${crypto.randomUUID().replaceAll("-", "").slice(0, 10)}`;
function lines() { return $("#script").value.split("\n").map((line) => line.trim()).filter(Boolean); }
function retime() { const copy = lines(); const count = Math.max(1, copy.length); const duration = Math.max(1, count * 3); state.topic.duration = duration; state.topic.segments = (copy.length ? copy : [""]).map((text, index) => ({ text, start: +(index * duration / count).toFixed(3), end: +((index + 1) * duration / count).toFixed(3) })); }
function defaultSlide(startSentence = 1) { return { id: token("slide"), startSentence, enterEffect: "fade", layers: [{ id: token("text"), type: "text", text: "", font: "default", color: "#090909", fontSize: 1.2, x: 6, y: 16, w: 88, h: 14 }, { id: token("media"), type: "image", src: "assets/placeholder-left.svg", x: 6, y: 34, w: 88, h: 38, zoom: 1, offsetX: 0, offsetY: 0 }] }; }
function slideMedia(slide) { let media = slide.layers.find((layer) => layer.type === "image"); if (!media) { media = { id: token("media"), type: "image", src: "assets/placeholder-left.svg", x: 6, y: 34, w: 88, h: 38, zoom: 1, offsetX: 0, offsetY: 0 }; slide.layers.push(media); } return media; }
function slideText(slide) { return slide.layers.find((layer) => layer.type === "text"); }
function assetUrl(path) { return `/project/${encodeURIComponent(project)}/${String(path || "").split("/").map(encodeURIComponent).join("/")}`; }
function renderSlides() { const max = Math.max(1, lines().length); $("#slides").innerHTML = state.topic.slides.map((slide, index) => { const text = slideText(slide); const media = slideMedia(slide); return `<article class="custom-slide" data-id="${slide.id}"><header><strong>Slide ${index + 1}</strong><button class="button tiny danger" data-remove type="button">Xoá</button></header><div class="custom-row"><label>Bắt đầu từ câu<input data-start type="number" min="1" max="${max}" value="${slide.startSentence}" /></label><label>Hiệu ứng vào<select data-effect>${["none","fade","zoom","rise","swipe"].map((effect) => `<option ${slide.enterEffect === effect ? "selected" : ""}>${effect}</option>`).join("")}</select></label></div><label>Chữ phủ<textarea data-text rows="3" maxlength="240" placeholder="Viết chữ cho slide này">${escapeHtml(text?.text || "")}</textarea></label><div class="custom-row"><label>Màu chữ<input data-color type="color" value="${text?.color || "#090909"}" /></label><label>Cỡ chữ<input data-size type="range" min="0.5" max="2" step="0.05" value="${text?.fontSize || 1.2}" /></label></div><label>Ảnh / media<div class="custom-image-row"><img src="${assetUrl(media?.src)}" alt="" /><input data-image type="file" accept="image/png,image/jpeg,image/webp" /></div></label></article>`; }).join(""); $("#previewCount").textContent = `${state.topic.slides.length} slide`; }
function queueSave(delay = 350) { clearTimeout(state.timer); $("#status").textContent = "Đang chờ tự lưu…"; state.timer = setTimeout(save, delay); }
async function save() { if (state.saving || !state.topic) return; state.saving = true; retime(); try { const result = await api(`/api/projects/${encodeURIComponent(project)}/topic`, { method: "PUT", body: JSON.stringify({ ...state.topic, projectType: "custom" }) }); state.topic = result.topic; $("#status").textContent = "Đã tự lưu"; renderSlides(); sendPreview(); } catch (error) { $("#status").textContent = error.message; } finally { state.saving = false; } }
function sendPreview(slideId = state.selected) { state.selected = slideId || state.topic.slides[0]?.id || ""; $("#preview").contentWindow?.postMessage({ type: "tho-topic-update", topic: state.topic, slideId: state.selected, time: 0 }, location.origin); }
function fileData(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
$("#script").addEventListener("input", () => { retime(); renderSlides(); queueSave(); });
$("#addSlide").addEventListener("click", () => { const count = state.topic.slides.length; state.topic.slides.push(defaultSlide(Math.min(Math.max(1, lines().length), count + 1))); renderSlides(); queueSave(50); });
$("#slides").addEventListener("input", (event) => { const card = event.target.closest("[data-id]"); const slide = state.topic.slides.find((item) => item.id === card?.dataset.id); if (!slide) return; const text = slideText(slide); if (event.target.matches("[data-start]")) slide.startSentence = Number(event.target.value) || 1; if (event.target.matches("[data-effect]")) slide.enterEffect = event.target.value; if (event.target.matches("[data-text]")) text.text = event.target.value; if (event.target.matches("[data-color]")) text.color = event.target.value; if (event.target.matches("[data-size]")) text.fontSize = Number(event.target.value); state.selected = slide.id; sendPreview(); queueSave(); });
$("#slides").addEventListener("click", (event) => { const card = event.target.closest("[data-id]"); const slide = state.topic.slides.find((item) => item.id === card?.dataset.id); if (!slide) return; if (event.target.matches("[data-remove]")) { state.topic.slides = state.topic.slides.filter((item) => item !== slide); if (!state.topic.slides.length) state.topic.slides = [defaultSlide(1)]; renderSlides(); queueSave(50); return; } state.selected = slide.id; sendPreview(); });
$("#slides").addEventListener("change", async (event) => { if (!event.target.matches("[data-image]")) return; const card = event.target.closest("[data-id]"); const slide = state.topic.slides.find((item) => item.id === card?.dataset.id); const file = event.target.files?.[0]; if (!slide || !file) return; try { $("#status").textContent = "Đang tải ảnh…"; const uploaded = await api(`/api/projects/${encodeURIComponent(project)}/upload`, { method: "POST", body: JSON.stringify({ kind: "leftImage", name: file.name, data: await fileData(file) }) }); slideMedia(slide).src = uploaded.path; state.selected = slide.id; renderSlides(); queueSave(20); } catch (error) { $("#status").textContent = error.message; } });
$("#render").addEventListener("click", async () => { await save(); location.href = `/?project=${encodeURIComponent(project)}`; });
async function load() { if (!project) { location.href = "/"; return; } try { const result = await api(`/api/projects/${encodeURIComponent(project)}/topic`); if (result.topic.projectType !== "custom") { location.replace(`/project/${encodeURIComponent(project)}/`); return; } state.topic = result.topic; state.topic.slides = Array.isArray(state.topic.slides) && state.topic.slides.length ? state.topic.slides : [defaultSlide(1)]; $("#title").textContent = project; $("#script").value = state.topic.segments.map((segment) => segment.text || "").join("\n"); $("#preview").src = `/index.html?topic=${encodeURIComponent(`/project/${project}/topic.json`)}&preview=1`; $("#preview").addEventListener("load", () => { sendPreview(); setTimeout(sendPreview, 250); setTimeout(sendPreview, 900); }); renderSlides(); $("#status").textContent = "Tự động lưu đã bật"; } catch (error) { $("#status").textContent = error.message; } }
load();
